###theme: jekyll-theme-cayman
# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://llh1985.github.io/
date_format: "ordinal"
title: 陋室
subtitle: "蹉跎岁月"
description: "小狂的个人博客"
keywords: 小狂, ivan, ivan Liu, 刘立辉
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 10

# ---------------- #
#      Author      #
# ---------------- #
author: ivan Liu
organization: ivan
organization_url: llh1985.github.io 
github_username: llh1985
location: beijing, China
email: llh1985@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: llh1985/llh1985.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: llh1985
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: ivan
    repo: blog-comments
    oauth:
        client_id: d1dd37a666f752266c61
        client_secret: 3f1f75cedf98b5c96871e3ddedd8fb7ea8d8580c
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
